#!/usr/bin/env bash
# A program the prints Fizzbuzz
a=1
while [ $a -lt 101 ]
do
	if [ $((a%3)) == 0 ] && [ $((a%5)) == 0 ]
	then
		echo "FizzBuzz"
	elif [ $((a%5)) == 0 ]
	then
		echo "Fizz"
	elif [ $((a%3)) == 0 ]
	then
		echo "Buzz"
	else
		echo "$a"
	fi
	((a++))
done
