#!/usr/bin/env bash
# a loop that prints number
a=1
while [ $a -lt 21 ]
do
	case $a in
	4)
		echo $a
		echo "bad luck from China"
		;;
	9)
		echo $a
		echo "bad luck from Japan"
		;;
	17)
		echo $a
		echo "bad luck from Italy"
		;;
	*)
		echo $a
		;;
	esac

	((a++))
done
